server.port=${SERVER_PORT:8081}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:validate}
spring.jpa.properties.hibernate.dialect=${JPA_DIALECT:org.hibernate.dialect.MySQLDialect}
spring.jpa.properties.hibernate.jdbc.time_zone=${JPA_TIME_ZONE:UTC}

inventory.security.api-key=${INVENTARIO_API_KEY}
