spring.application.name=${SPRING_APPLICATION_NAME:inventario}
spring.profiles.default=dev
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR
spring.jpa.open-in-view=false

spring.flyway.enabled=${FLYWAY_ENABLED:true}
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=${FLYWAY_BASELINE_ON_MIGRATE:true}
spring.flyway.validate-on-migrate=${FLYWAY_VALIDATE_ON_MIGRATE:true}

inventory.security.api-key=${INVENTARIO_API_KEY:}
inventory.security.header-name=${INVENTARIO_API_KEY_HEADER:X-API-Key}

springdoc.swagger-ui.path=${SWAGGER_UI_PATH:/swagger-ui.html}